name: Generate and Publish Milestone Document

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  milestone:
    if: github.repository_owner == 'ory'
    name: Generate and Publish Milestone Document
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.TOKEN_PRIVILEGED }}
      - name: Milestone Documentation Generator
        uses: ory/milestone-action@0d8347b062af50e640f1658e8308ba391664d196 # v0.0.19
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          outputFile: docs/docs/milestones.md
      - name: Commit Milestone Documentation
        uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10.0.0
        with:
          message: "autogen(docs): update milestone document"
          author_name: aeneasr
          author_email: "3372410+aeneasr@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_PRIVILEGED }}
