name: Conventional Commits

on:
  pull_request_target:
    types:
      - edited
      - opened
      - ready_for_review
      - reopened
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kevgo/action-test@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
