name: Conventional commits

on:
  pull_request_target:
    types:
      - edited
      - opened
      - ready_for_review
      - reopened
      - synchronize
  # pull_request: # for debugging, uses config in local branch but supports only Pull Requests from this repo

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ory/ci/conventional_commits@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
