name: Check format

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  check-format:
    runs-on: ubuntu-latest
    name: Check format
    steps:
      - uses: actions/checkout@v2
      - uses: ory/prettier-styles@v1.0.1
